name: Build Brunch-mac using Github Actions
on:
  workflow_dispatch:
    branches:
      - 'Live'
    paths-ignore:
      - 'README.md'
concurrency:
  group: environment-${{ github.ref }}
  cancel-in-progress: true
jobs:
  prepare-kernels:
    name: Prepare Kernels
    runs-on: ubuntu-22.04
    outputs:
      matrix: ${{ steps.kernels.outputs.matrix }}
    steps:
      - name: Install dependencies
        run: |
          yes | DEBIAN_FRONTEND=noninteractive sudo apt update
          #yes | DEBIAN_FRONTEND=noninteractive sudo apt dist-upgrade
          yes | DEBIAN_FRONTEND=noninteractive sudo apt install gcc-12 g++-12 git fakeroot build-essential ncurses-dev xz-utils libssl-dev bc flex libelf-dev bison sbsigntool
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 110 --slave /usr/bin/g++ g++ /usr/bin/g++-12 --slave /usr/bin/gcov gcov /usr/bin/gcov-12
      - name: Checkout Brunch-mac source code
        uses: actions/checkout@v3
      - name: Download kernels and apply patches
        run: ./prepare_kernels.sh
      - name: Define kernels matrix
        id: kernels
        run: echo "matrix=$(echo [\"$(ls -d ./kernels/*  | cut -f3 -d'/' | sed -Ez '$ s/\n+$//' | sed -z 's#\n#","#g')\"])" >> $GITHUB_OUTPUT
      - name: Compress kernels source files
        run: tar zcf /tmp/kernels-source.tar.gz kernels
      - name: Upload kernels source
        uses: actions/upload-artifact@v3
        with:
          name: kernels-source
          path: /tmp/kernels-source.tar.gz
          if-no-files-found: error
  build-kernels:
    name: Build Kernels
    needs: prepare-kernels
    runs-on: ubuntu-22.04
    strategy:
        matrix:
            kernel: ${{ fromJson(needs.prepare-kernels.outputs.matrix) }}
    steps:
      - name: Install dependencies
        run: |
          yes | DEBIAN_FRONTEND=noninteractive sudo apt update
          #yes | DEBIAN_FRONTEND=noninteractive sudo apt dist-upgrade
          yes | DEBIAN_FRONTEND=noninteractive sudo apt install gcc-12 g++-12 git fakeroot build-essential ncurses-dev xz-utils libssl-dev bc flex libelf-dev bison sbsigntool
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 110 --slave /usr/bin/g++ g++ /usr/bin/g++-12 --slave /usr/bin/gcov gcov /usr/bin/gcov-12
      - name: Checkout Brunch-mac source code
        uses: actions/checkout@v3
      - name: Download kernels source
        uses: actions/download-artifact@v3
        with:
          name: kernels-source
          path: /tmp
      - name: Extract kernels source files
        run: |
          tar -zxf /tmp/kernels-source.tar.gz
          rm -f /tmp/kernels-source.tar.gz
      - name: Install Secure Boot certificate
        env:
          BRUNCH_PRIV: ${{ secrets.BRUNCH_PRIV }}
          BRUNCH_PEM: ${{ secrets.BRUNCH_PEM }}
        run: |
          sudo ln -s $RUNNER_TEMP /persist
          mkdir /persist/keys
          echo "$BRUNCH_PRIV" | base64 -d > /persist/keys/brunch.priv
          echo "$BRUNCH_PEM" | base64 -d > /persist/keys/brunch.pem
      - name: Build kernels
        run: ./build_kernels.sh ${{ matrix.kernel }}
      - name: Clear keys
        run: rm -r /persist/keys
      - name: Compress built kernel
        run: tar zcf /tmp/built-kernel-${{ matrix.kernel }}.tar.gz kernels/${{ matrix.kernel }}
      - name: Upload kernels source
        uses: actions/upload-artifact@v3
        with:
          name: built-kernel-${{ matrix.kernel }}
          path: /tmp/built-kernel-${{ matrix.kernel }}.tar.gz
          if-no-files-found: error
  build-brunch:
    name: Build Brunch-mac
    needs: build-kernels
    runs-on: ubuntu-22.04
    steps:
      - name: Install dependencies
        run: |
          yes | DEBIAN_FRONTEND=noninteractive sudo apt update
          #yes | DEBIAN_FRONTEND=noninteractive sudo apt dist-upgrade
          yes | DEBIAN_FRONTEND=noninteractive sudo apt install gcc-12 g++-12 git fakeroot build-essential ncurses-dev xz-utils libssl-dev bc flex libelf-dev bison sbsigntool python3-protobuf
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 110 --slave /usr/bin/g++ g++ /usr/bin/g++-12 --slave /usr/bin/gcov gcov /usr/bin/gcov-12
          pip3 install --upgrade google-api-python-client
      - name: Free some disk space
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc
          sudo apt clean
      - name: Checkout Brunch-mac source code
        uses: actions/checkout@v3
      - name: Download built kernels
        uses: actions/download-artifact@v3
        with:
          path: /tmp
      - name: Copy built kernels
        run: |
          for file in /tmp/built-kernel-*/built-kernel-*.tar.gz
          do
            tar zxf $file
            rm -f $file
          done
          rm -r /tmp/kernels-source/kernels-source.tar.gz
      - name: Build brunch-mac
        run: sudo bash build_brunch.sh
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: brunch-build
          path: out/brunch_r*.tar.gz
          if-no-files-found: error
  release:
    name: Make a Brunch-mac release
    permissions:
      contents: write
    needs: build-brunch
    runs-on: ubuntu-22.04
    steps:
      - name: Download built artifacts
        uses: actions/download-artifact@v3
        with:
          name: brunch-build
      - name: Generate release details
        run: |
          RELEASE_FILE=$(ls brunch_r*.tar.gz)
          RELEASE_VERSION=$(echo "$RELEASE_FILE" | sed 's/[^0-9.]//g')
          MAJOR_VERSION=$(cut -c 2- <<< "$RELEASE_VERSION")
          # Check if the major version tag already exists
          if git rev-parse -q --verify "refs/tags/r${MAJOR_VERSION}" > /dev/null; then
            # If it exists, it's not the first release of this major version
            # Determine the last decimal number used for this major version
            LAST_RELEASE_TAG=$(git for-each-ref --sort=-taggerdate --format '%(refname:short)' "refs/tags/r${MAJOR_VERSION}.*" | head -n 1)
            LAST_DECIMAL=$(cut -d. -f3 <<< "$LAST_RELEASE_TAG")
            NEW_DECIMAL=$((LAST_DECIMAL + 1))
            RELEASE_VERSION="r${MAJOR_VERSION}.${NEW_DECIMAL}"
          else
            # If it's the first release of this major version, set it to "rX" (no decimal)
            RELEASE_VERSION="r${MAJOR_VERSION}"
          fi
          NEW_RELEASE_NAME="Brunch-mac ${RELEASE_VERSION}"
          NEW_RELEASE_FILE="Brunch-mac_${RELEASE_VERSION}.tar.gz"
          echo "Found brunch release: ${RELEASE_FILE} with version ${RELEASE_VERSION}"
          echo "Renaming release file to: $NEW_RELEASE_FILE"
          mv "$RELEASE_FILE" "$NEW_RELEASE_FILE"
          echo "RELEASE_NAME=${NEW_RELEASE_NAME}" >> $GITHUB_ENV
          echo "RELEASE_TAG=${RELEASE_VERSION}" >> $GITHUB_ENV
        id: generate-release-details
      - name: Create a release and upload artifacts as assets
        uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ env.RELEASE_FILE }}"
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          tag: "${{ env.RELEASE_TAG }}"
          name: "${{ env.RELEASE_NAME }}"
          commit: "${{ github.ref_name }}"
          body: "${{ github.event.head_commit.message }}"
